name: Cookie Clicker

on:
  issues:
    types: [opened]

jobs:
  update-leaderboard:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get install -y jq curl

      - name: Check permissions
        id: check-permissions
        run: |
          # Extract the username of the user who clicked
          USERNAME=$(jq -r '.issue.user.login' "$GITHUB_EVENT_PATH")
          
          # Use GitHub API to check user permissions
          REPO_API_URL="https://api.github.com/repos/${{ github.repository }}/collaborators/$USERNAME/permission"
          RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.ACTIONS_PAT }}" "$REPO_API_URL")
          
          # Check if the response contains the permission information
          if echo "$RESPONSE" | grep -q '"permission": "admin"\|"push"'; then
            echo "User $USERNAME has sufficient permissions."
          else
            echo "User $USERNAME does not have sufficient permissions."
            exit 1
          fi

      - name: Update leaderboard
        run: |
          CLICKS_FILE=clicks.txt
          LEADERBOARD_FILE=README.md

          # Extract the username of the user who clicked
          USERNAME=$(jq -r '.issue.user.login' "$GITHUB_EVENT_PATH")

          # Update the clicks file
          if grep -q "^$USERNAME " "$CLICKS_FILE"; then
            awk -v user="$USERNAME" -v new_count="$(( $(grep "^$USERNAME " "$CLICKS_FILE" | awk '{print $2}') + 1 ))" \
              '$1 == user { $2 = new_count } 1' "$CLICKS_FILE" > temp.txt && mv temp.txt "$CLICKS_FILE"
          else
            echo "$USERNAME 1" >> "$CLICKS_FILE"
          fi

          # Sort and update the leaderboard in the README
          sort -k2 -n -r "$CLICKS_FILE" > sorted_clicks.txt
          LEADERBOARD=$(awk '{print NR ". " $1 ": " $2 " clicks"}' sorted_clicks.txt)

          # Escape special characters in the leaderboard for insertion
          LEADERBOARD_ESCAPED=$(echo "$LEADERBOARD" | awk '{gsub(/&/, "\\&"); gsub(/\//, "\\/"); gsub(/\\/, "\\\\"); print}')

          # Insert the leaderboard into the README using awk
          awk -v leaderboard="$LEADERBOARD_ESCAPED" '
            /<!-- LEADERBOARD_START -->/ { print; print leaderboard; next }
            /<!-- LEADERBOARD_END -->/ { print; next }
            { print }
          ' "$LEADERBOARD_FILE" > temp.md && mv temp.md "$LEADERBOARD_FILE"

          # Commit the changes
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "$CLICKS_FILE" "$LEADERBOARD_FILE"
          git commit -m "Update leaderboard for $USERNAME"

      - name: Push changes
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
        run: |
          echo "Using PAT for git push"
          git push https://${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }}.git HEAD:main
